name: 'pnpm dependency list to dependency graph'
description: 'Convert json formated dependecy list to github dependecy graph'
author: 'mptasinski'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  lockFilePath:
    required: false
    description: 'path to pnpm-lock file'
    default: 'pnpm-lock.yaml'
runs:
  using: 'node16'
  main: 'dist/index.js'
