name: 'pnpm dependency list to dependency graph'
description: 'Convert json formated dependecy list to github dependecy graph'
author: 'mptasinski'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Actions runner."
    required: false
    default: ${{ github.token }}
  repoName:
    description: "repository Name"
    required: false
    default: ${{ github.event.repository.name }}
  repoVersion:
    description: "repository version"
    required: false
    default: '1.0.0'
  lockFilePath:
    required: false
    description: 'path to pnpm-lock file'
    default: 'pnpm-lock.yaml'
runs:
  using: 'node16'
  main: 'dist/index.js'
